# -*- coding: utf-8 -*-
{
    'name': 'Fire Alarm and Fire Fighting',
    'version': '14.0.1.0.22',
    'author': 'CPA Books',
    'summary': 'Fire alarm and fire fighting jobs from inspection and quotation to invoice',
    'sequence': -95,
    'description': """
CPABooks FAFF — One job → One wizard → Start to Finish.
CRM → Inspection → Estimate → Quotation → Project → Materials →
Execute → Test → Handover → Invoice → Payment.
    """,
    'category': 'Services/Fire Safety',
    'website': 'https://www.cpabooks.co',
    'support': 'info@cpabooks.org',
    'license': 'LGPL-3',
    'price': 0.00,
    'currency': 'USD',
    'images': ['static/description/banner_store.jpg'],
    'live_test_url': 'https://www.cpabooks.org/apps/faff',
    'depends': [
        'crm',
        'sale_management',
        'project',
        'purchase',
        'stock',
        'account',
        'mail',
        'hr',
        'sequences_cpa',
    ],
    'data': [
        'security/faff_security.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/job_type_data.xml',
        'data/default_task_data.xml',
        'views/faff_backend_assets.xml',
        'views/faff_config_views.xml',
        'views/faff_job_views.xml',
        'views/faff_visit_views.xml',
        'views/faff_estimate_views.xml',
        'views/faff_material_views.xml',
        'views/faff_testing_views.xml',
        'views/faff_completion_views.xml',
        'views/faff_wizard_views.xml',
        'views/faff_process_flow_views.xml',
        'views/faff_sample_loader_views.xml',
        'views/crm_lead_views.xml',
        'views/faff_mis_report_views.xml',
        'views/menus.xml',
        'report/faff_completion_report.xml',
        'report/faff_completion_templates.xml',
        'report/faff_mis_report.xml',
        'report/faff_mis_templates.xml',
    ],
    'demo': [],
    'qweb': [
        'static/src/xml/faff_dashboard.xml',
        'static/src/xml/faff_process_flow.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}
