# -*- coding: utf-8 -*-
{
    'name': 'Switchgear Manufacturing',
    'summary': 'Switchgear flow from enquiry to delivery, quality, and payment',
    'sequence': -88,
    'description': """
Switchgear processing cycle on standard Odoo:
CRM, job estimate, quotation, design, BoM, manufacturing,
purchase requisition, quality check, stock, invoice, and payment.
    """,
    'category': 'Manufacturing',
    'version': '14.0.1.0.1',
    'author': 'CPA Books',
    'website': 'https://www.cpabooks.co',
    'support': 'info@cpabooks.org',
    'price': 0.00,
    'currency': 'USD',
    'depends': [
        'web',
        'crm',
        'sale_management',
        'sale_crm',
        'sale_project',
        'mrp',
        'stock',
        'purchase',
        'account',
        'project',
        'mail',
        'hr',
        'hr_timesheet',
    ],
    'data': [
        'security/menu_groups.xml',
        'security/ir.model.access.csv',
        'wizard/create_purchase_order.xml',
        'views/switchgear_demo_wizard_views.xml',
        'data/ir_sequence_data.xml',
        'views/switchgear_core_views.xml',
        'data/flowchart_kanban_data.xml',
        'views/crm_lead_views.xml',
        'views/mrp_production_views.xml',
        'views/mrp_bom_views.xml',
        'views/job_estimate_views.xml',
        'views/sale_order_views.xml',
        'views/switchgear_design_document_views.xml',
        'views/stock_picking_views.xml',
        'views/purchase_order_views.xml',
        'views/quality_views.xml',
        'views/project_views.xml',
        'views/flowchart_views.xml',
        # Tutorial menuitem parents menu_flowchart_kanban_root (created above).
        'views/switchgear_tutorial_wizard_views.xml',
        'views/menu_groups.xml',
        'views/switchgear_menu_icon.xml',
        'views/switchgear_project_menus.xml',
        'views/switchgear_configuration_action.xml',
        'views/switchgear_configuration_menu.xml',
        'views/switchgear_activity_menus.xml',
        'views/switchgear_odooapp_demo_menu.xml',
        'views/switchgear_hide_top_menus.xml',
        'views/cpabooks_progress_status_views.xml',
        'views/switchgear_assets.xml',
        'report/mrp_report_bom_structure.xml',
        'report/mrp_production_templates.xml',
        'report/qc_label_templates.xml',
        'report/report_job_order.xml',
        'report/report_menu.xml',
    ],
    'qweb': [
        'static/src/xml/switchgear_dashboard.xml',
    ],
    'images': ['static/description/banner_store.jpg'],
    'live_test_url': 'https://www.cpabooks.org/apps/switchgear',
    'installable': True,
    'application': True,
    'auto_install': False,
    'post_init_hook': 'post_init_hook',
    'pre_init_hook': 'pre_init_hook',
    'license': 'LGPL-3',
}
